# This workflow will install dependencies, build the project and run tests

name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cmake and gtest
      run: |
        sudo apt-get install -y cmake libgtest-dev
    - name: Build project
      run: |
        cmake .
        make
    - name: Run tests
      run: |
        bin/ut_factory_injector
